/mnt/c/Users/rabbit/.gemini/antigravity/scratch/IAPAnalyzer/.theos/obj/debug/arm64/Tweak.x.58d93b3a.o: \
  /mnt/c/Users/rabbit/.gemini/antigravity/scratch/IAPAnalyzer/.theos/obj/debug/arm64/Tweak.x.m \
  /root/theos/Prefix.pch \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/kcdata.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/libunwind.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/uuid.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/sys__pthread.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/netinet6.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/secure.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/machine.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/device.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach_debug.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach_machine.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/bank.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_posix_sys_types.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/_types.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_posix_pthread.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/netinet.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/net.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_c_xlocale.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_cdefs.modulemap \
  /root/theos/vendor/include/UserNotificationsUIKit/module.modulemap \
  /root/theos/vendor/include/UserNotificationsKit/module.modulemap \
  /root/theos/vendor/include/UIFoundation/module.modulemap \
  /root/theos/vendor/include/TextInput/module.modulemap \
  /root/theos/vendor/include/TelephonyUI/module.modulemap \
  /root/theos/vendor/include/StoreKitUI/module.modulemap \
  /root/theos/vendor/include/SpringBoardUIServices/module.modulemap \
  /root/theos/vendor/include/SpringBoardUI/module.modulemap \
  /root/theos/vendor/include/SpringBoardHome/module.modulemap \
  /root/theos/vendor/include/SpringBoardFoundation/module.modulemap \
  /root/theos/vendor/include/SplashBoard/module.modulemap \
  /root/theos/vendor/include/rocketbootstrap/module.modulemap \
  /root/theos/vendor/include/PreferencesUI/module.modulemap \
  /root/theos/vendor/include/Preferences/module.modulemap \
  /root/theos/vendor/include/PhotoLibraryServices/module.modulemap \
  /root/theos/vendor/include/PhotoLibrary/module.modulemap \
  /root/theos/vendor/include/PersonaUI/module.modulemap \
  /root/theos/vendor/include/PersonaKit/module.modulemap \
  /root/theos/vendor/include/PersistentConnection/module.modulemap \
  /root/theos/vendor/include/PassKitUIFoundation/module.modulemap \
  /root/theos/vendor/include/PassKitUI/module.modulemap \
  /root/theos/vendor/include/PassKitCore/module.modulemap \
  /root/theos/vendor/include/OSAnalytics/module.modulemap \
  /root/theos/vendor/include/OnBoardingKit/module.modulemap \
  /root/theos/vendor/include/MobileTimer/module.modulemap \
  /root/theos/vendor/include/MobileIcons/module.modulemap \
  /root/theos/vendor/include/MobileCoreServices/module.modulemap \
  /root/theos/vendor/include/MediaRemote/module.modulemap \
  /root/theos/vendor/include/MediaPlayerUI/module.modulemap \
  /root/theos/vendor/include/MaterialKit/module.modulemap \
  /root/theos/vendor/include/LowPowerMode/module.modulemap \
  /root/theos/vendor/include/libundirect/module.modulemap \
  /root/theos/vendor/include/libroot/module.modulemap \
  /root/theos/vendor/include/libprefs/module.modulemap \
  /root/theos/vendor/include/libhooker/module.modulemap \
  /root/theos/vendor/include/libactivator/module.modulemap \
  /root/theos/vendor/include/IMSharedUtilities/module.modulemap \
  /root/theos/vendor/include/IMFoundation/module.modulemap \
  /root/theos/vendor/include/IMDaemonCore/module.modulemap \
  /root/theos/vendor/include/IMCore/module.modulemap \
  /root/theos/vendor/include/GeoServices/module.modulemap \
  /root/theos/vendor/include/FrontBoardServices/module.modulemap \
  /root/theos/vendor/include/FrontBoard/module.modulemap \
  /root/theos/vendor/include/Flipswitch/module.modulemap \
  /root/theos/vendor/include/ControlCenterUIKit/module.modulemap \
  /root/theos/vendor/include/ChatKit/module.modulemap \
  /root/theos/vendor/include/Celestial/module.modulemap \
  /root/theos/vendor/include/CameraUI/module.modulemap \
  /root/theos/vendor/include/CameraKit/module.modulemap \
  /root/theos/vendor/include/BulletinBoard/module.modulemap \
  /root/theos/vendor/include/BatteryCenter/module.modulemap \
  /root/theos/vendor/include/BaseBoardUI/module.modulemap \
  /root/theos/vendor/include/BaseBoard/module.modulemap \
  /root/theos/vendor/include/BackBoardServices/module.modulemap \
  /root/theos/vendor/include/AssistantServices/module.modulemap \
  /root/theos/vendor/include/AssertionServices/module.modulemap \
  /root/theos/vendor/include/AppSupport/module.modulemap \
  /root/theos/vendor/include/AppList/module.modulemap \
  /root/theos/vendor/include/ApplePushService/module.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach-o/compact_unwind_encoding.modulemap \
  /root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach-o/dyld.modulemap \
  /root/theos/vendor/include/substrate.h \
  /root/theos/vendor/lib/CydiaSubstrate.framework/Modules/module.modulemap \
  /root/theos/vendor/lib/CydiaSubstrate.framework/Headers/CydiaSubstrate.h

/root/theos/Prefix.pch:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/kcdata.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/libunwind.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/uuid.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/sys__pthread.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/netinet6.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/secure.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/machine.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/device.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach_debug.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach_machine.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/bank.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_posix_sys_types.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/_types.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_posix_pthread.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/netinet.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/net.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_c_xlocale.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/darwin_cdefs.modulemap:

/root/theos/vendor/include/UserNotificationsUIKit/module.modulemap:

/root/theos/vendor/include/UserNotificationsKit/module.modulemap:

/root/theos/vendor/include/UIFoundation/module.modulemap:

/root/theos/vendor/include/TextInput/module.modulemap:

/root/theos/vendor/include/TelephonyUI/module.modulemap:

/root/theos/vendor/include/StoreKitUI/module.modulemap:

/root/theos/vendor/include/SpringBoardUIServices/module.modulemap:

/root/theos/vendor/include/SpringBoardUI/module.modulemap:

/root/theos/vendor/include/SpringBoardHome/module.modulemap:

/root/theos/vendor/include/SpringBoardFoundation/module.modulemap:

/root/theos/vendor/include/SplashBoard/module.modulemap:

/root/theos/vendor/include/rocketbootstrap/module.modulemap:

/root/theos/vendor/include/PreferencesUI/module.modulemap:

/root/theos/vendor/include/Preferences/module.modulemap:

/root/theos/vendor/include/PhotoLibraryServices/module.modulemap:

/root/theos/vendor/include/PhotoLibrary/module.modulemap:

/root/theos/vendor/include/PersonaUI/module.modulemap:

/root/theos/vendor/include/PersonaKit/module.modulemap:

/root/theos/vendor/include/PersistentConnection/module.modulemap:

/root/theos/vendor/include/PassKitUIFoundation/module.modulemap:

/root/theos/vendor/include/PassKitUI/module.modulemap:

/root/theos/vendor/include/PassKitCore/module.modulemap:

/root/theos/vendor/include/OSAnalytics/module.modulemap:

/root/theos/vendor/include/OnBoardingKit/module.modulemap:

/root/theos/vendor/include/MobileTimer/module.modulemap:

/root/theos/vendor/include/MobileIcons/module.modulemap:

/root/theos/vendor/include/MobileCoreServices/module.modulemap:

/root/theos/vendor/include/MediaRemote/module.modulemap:

/root/theos/vendor/include/MediaPlayerUI/module.modulemap:

/root/theos/vendor/include/MaterialKit/module.modulemap:

/root/theos/vendor/include/LowPowerMode/module.modulemap:

/root/theos/vendor/include/libundirect/module.modulemap:

/root/theos/vendor/include/libroot/module.modulemap:

/root/theos/vendor/include/libprefs/module.modulemap:

/root/theos/vendor/include/libhooker/module.modulemap:

/root/theos/vendor/include/libactivator/module.modulemap:

/root/theos/vendor/include/IMSharedUtilities/module.modulemap:

/root/theos/vendor/include/IMFoundation/module.modulemap:

/root/theos/vendor/include/IMDaemonCore/module.modulemap:

/root/theos/vendor/include/IMCore/module.modulemap:

/root/theos/vendor/include/GeoServices/module.modulemap:

/root/theos/vendor/include/FrontBoardServices/module.modulemap:

/root/theos/vendor/include/FrontBoard/module.modulemap:

/root/theos/vendor/include/Flipswitch/module.modulemap:

/root/theos/vendor/include/ControlCenterUIKit/module.modulemap:

/root/theos/vendor/include/ChatKit/module.modulemap:

/root/theos/vendor/include/Celestial/module.modulemap:

/root/theos/vendor/include/CameraUI/module.modulemap:

/root/theos/vendor/include/CameraKit/module.modulemap:

/root/theos/vendor/include/BulletinBoard/module.modulemap:

/root/theos/vendor/include/BatteryCenter/module.modulemap:

/root/theos/vendor/include/BaseBoardUI/module.modulemap:

/root/theos/vendor/include/BaseBoard/module.modulemap:

/root/theos/vendor/include/BackBoardServices/module.modulemap:

/root/theos/vendor/include/AssistantServices/module.modulemap:

/root/theos/vendor/include/AssertionServices/module.modulemap:

/root/theos/vendor/include/AppSupport/module.modulemap:

/root/theos/vendor/include/AppList/module.modulemap:

/root/theos/vendor/include/ApplePushService/module.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach-o/compact_unwind_encoding.modulemap:

/root/theos/sdks/iPhoneOS16.5.sdk/usr/include/mach-o/dyld.modulemap:

/root/theos/vendor/include/substrate.h:

/root/theos/vendor/lib/CydiaSubstrate.framework/Modules/module.modulemap:

/root/theos/vendor/lib/CydiaSubstrate.framework/Headers/CydiaSubstrate.h:
